@startsalt GUI Layout
{
  [Convert °]|
  [ Quit    ]
  
  {+
    Min/Max/Avg
    {
      <<tempicon
      .....X......
      ....X.X.....
      ....X.X.....
      ....X.X.....
      ....XXX.....
      ....XXX.....
      ...XXXXX....
      ..XXXXXXX...
      ...XXXXX....
      ....XXX.....
      >>|
      20°C
    }
  }|
  {+
    Min/Max/Avg
    {
      <<
      .....X......
      ....X.X.....
      ....X.X.....
      ...X...X....
      ...X...X....
      ..X.....X...
      ..X.....X...
      ..X.....X...
      ...X...X....
      ....XXX.....
      >>|
      50%
    }
  }
  
  {+
    TempGraph
  }|
  {+
    RHumGraph
  }
  
  
}
@endsalt